return {
'/home/harshit/Harshit_Work/Funny_Stuff/z_SupermodelCats/You might remember my boy Piper from a post I made when he was a kitten. Well, now he’s a grown man!.jpg',
'/home/harshit/Harshit_Work/Funny_Stuff/z_wallpaper/from Awesome/icemountains.jpg',
'/home/harshit/Harshit_Work/Funny_Stuff/z_wallpaper/from Awesome/firewatchnight.png',
'/home/harshit/Harshit_Work/Funny_Stuff/z_aww/Orange cat appreciation post - here is Bug and Ropey!.jpg',
'/home/harshit/Harshit_Work/Funny_Stuff/z_CatTrap/Work gave me a free bag and it’s been claimed already.jpg',
'/home/harshit/Harshit_Work/Funny_Stuff/z_politecats/Creamer would like to tell me that I’m not allowed to do anymore schoolwork.jpg',
'/home/harshit/Harshit_Work/Funny_Stuff/Cats/Opposites attract ... 🤘🏻❤🩰.jpg',
"/home/harshit/Harshit_Work/Funny_Stuff/z_Kitten/Brothers tired after a long play.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_SkyPorn/Sunset in Seattle 💕.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_terrariums/I got this wall fishbowl when I was a kid, a terrarium seems like a better use..jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_kittens/June Bug and George, brother and sister.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_aww/(OC) What breed do you think she is？ A friend of ours is giving her up may take the dog with me. It's mixed but not sure what with.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_Catswithjobs/Fire Prevention Officer Max.png",
"/home/harshit/Harshit_Work/Funny_Stuff/z_cats/Thought I’d gone mad 3 weeks ago when I couldn’t find this shallot while making dinner. This morning I hear a noise… he’s stolen it as a toy!.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_redpandas/I never really had a favorite animal until these little buddies came to our zoo!.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_cats/Found box, must sit.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_Astronomy/Lunar Shadows.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/9f5461b119d2926680e8b84f1bc58acb.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_cats/This is Xenia. Today, she curled up on her favorite chair to nap. She never woke up. She was 21 yrs old..jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_cats/Came home and my cat was sitting at my computer like he was using it. What do you think is in my search history now？.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_wallpaper/[3840x2160] Moony Zen Night.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/6a799ee77933857788c26817ce474784.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/d98144ebc8d1e27492345221ca4b379b.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_Catswithjobs/Shop inspectors.png",
"/home/harshit/Harshit_Work/Windows_Spotlight/b948e52bdfc800cb3d56af3796813d00.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_astrophotography/Pleiades.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_CatsBeingCats/Would you say no for anything she asks？.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/WallpaperStudio10-79633.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_aww/(oc) catch of the day.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_watercolorcats/Miss Tonks, looking particularly lovely in the afternoon light.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/Cats/The great hunter.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_aww/The shelter made a rule that these siblings had to be adopted together because they were inseparable. They sleep like this every night..jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/cd9e4cfe208606e724bc3e5a77f0f8e7.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_catsarealiens/This was the last thing I saw before I blacked out for three days.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_ThereIsnoCat/Rub a dub dub.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_WhatsWrongWithYourCat/We found this lady living in a dumpster. She has one eye and zero natural instincts. Couldn’t catch an animal if her life depended on it - so she brings us dead weeds instead..jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/854a33add5580e28247b23797db931ab.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_EarthPorn/An otherwordly morning in the swamps of the southern United States. [OC][2000x1336] @mattymeis.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_OneOrangeBraincell/Are you allowed to get up when your cat sleeps on you？.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_dustkitties/Just brushed. 💅 Everyone tell Minecraft that she’s pretty..jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/54087a9f5cfbf2d7e082c23201f22bb2.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/3dbc0d18beea1c7344afb1a86d16f20d.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_calvinandhobbes/Calvin the elephant.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_cats/a cat..jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_catpictures/Tiger, 32, has passed away this morning..jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_TIGHTPUSSY/Pot.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/1a257cfe4f697b986153fc09de098a0a.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_cats/I bought my sphynx a warm den. But the other cat decided it was a great soft lie-in..png",
"/home/harshit/Harshit_Work/Windows_Spotlight/2aabbcc4f269fde99737e6d1b678e47a.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/53960056acbcf3b7a4cd30f761c2e747.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_TacticalIssueCat/TIC General Leia demonstrating advanced loaf formation.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_OneOrangeBraincell/Taking bets on how long this tree lasts.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/d132196f7e90374051a58eaace36e073.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_vegetablegardening/been waiting for these butternut squash all damn year..jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_EarthPorn/Lake Sorvagsvatn, Faroe Islands [OC] [1800x1494].jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_watercolorcats/I see a full stylized pagoda on a cliff to the left, with two dragons facing each other to the right. Alia is apparently a fan of Japanese or Chinese art at this angle..png",
"/home/harshit/Harshit_Work/Funny_Stuff/z_vegetablegardening/My last harvest before the frost hit..jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/858d4ba13e58cc4295f276ce095c625e.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/a8da2c13315b5e53d1c9656dc800f385.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/f7c281aa441dda86e853377f4d23be71.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_TuxedoCats/Hi Everyone. Meet Noodles.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/0f270029e0692d429453b1a9717370c9.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_tuckedinkitties/She made herself a little cave in our comforter.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/584654cc053323dc1b7486de7965c0e8.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_redpandas/A Happy Family.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/e4a0a4bf9589b77a048e50d9d14dcea0.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/bf3439d6f30dd99ac1953b24e36e4fe9.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_noodlebones/So silly.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_redpandas/I know it’s monday, but hang in there 🌞.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_SupermodelCats/This is our thicc boi, his name is Ghost..jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_ThereIsnoCat/Camina？ I don’t see her？.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/Cats/I did it!.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_SkyPorn/Stunning iridescent clouds snapped above skies of Siberia's Belukha mountain.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/1dc7413cbbaed2694ef2a63b3de53aec.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_ThereIsnoCat/Wherever could she be？.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_redpandas/MFW summer vacation is over.jpg",
"/home/harshit/Harshit_Work/Windows_Spotlight/55caaffcbbf1d8d4093b639888796bc5.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_blackcats/My new little void!.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_ThereIsnoCat/Just a laundry basket.png",
"/home/harshit/Harshit_Work/Funny_Stuff/z_ThereIsnoCat/Definitely no cat here. Just some blankets..jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_ThereIsnoCat/Just one void, nothing more...jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_calvinandhobbes/What if my bones were in a Museum？.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_CatTrap/Kitten is telling me ALL about it! She loves her traps..jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_kittens/Same litter, and each one is unique!.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_calvinandhobbes/Calvin, I....jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_calvinandhobbes/Looks like something Calvin would make.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_calvinandhobbes/Dad’s constant positivity is kind of endearing.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_calvinandhobbes/Gravity.jpg",
"/home/harshit/Harshit_Work/Astrophotography/Dragonfish Coming At You in Infrared.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_astrophotography/Horse head and flame nebula IC 434.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_astrophotography/47 hours on Sh2-224 - The Rice Hat Nebula.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_calvinandhobbes/Look, Hobbes, this is my retirement fund..jpg",
"/home/harshit/Harshit_Work/Astrophotography/Cosmic Epic Unfolds in Infrared_ The Eagle Nebula.jpg",
"/home/harshit/Harshit_Work/Astrophotography/Bubbles Within Bubbles (annotated).jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_space/JWST - The 'Deep Field' image of SMACS 0723 actually has two parts since the NIRCam instrument has dual sensors. Take a look at these other galaxies. This is my first attempt at image processing..jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_astrophotography/SH 2-308： The Dolphin Head Nebula (654145).png",
"/home/harshit/Harshit_Work/Funny_Stuff/z_astrophotography/Solar prominence on the sun's eastern limb.jpg",
"/home/harshit/Harshit_Work/Astrophotography/Starburst galaxy Messier 94.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_astrophotography/Ghost Nebula.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_Astronomy/Melotte 15 Nebula With a DSLR.jpg",
"/home/harshit/Harshit_Work/Astrophotography/The Carina Nebula from the ground.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_astrophotography/Orion belt, 1 hour and 30mins.jpg",
"/home/harshit/Harshit_Work/Astrophotography/Selected/Hubble's View of Jupiter and Europa in August 2020.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_kittens/Oh to be two kittens kissing on a broom.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_CatsCalledFood/Meet Mr.Butterball Turkey.jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_CatTrap/Trapped this sexy beast..jpg",
"/home/harshit/Harshit_Work/Funny_Stuff/z_Kitten/A flat cat on her back....jpg",
}